# Generated by Django 6.0.4 on 2026-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('done', 'Done'), ('notdone', 'Not Done')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='to_do_list_doen',
        ),
        migrations.DeleteModel(
            name='to_do_list_not_doen',
        ),
    ]
